version: "3"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '8080:8080'
    restart: always
    environment:
      DOMAINS: 'n-okamoto.t.telsys.co.jp -> http://n-okamoto.t.telsys.co.jp:3333'
      STAGE: production
  node:
    build: node/.
    volumes:
      - ./node:/node
    working_dir: /node
    command: ["./node_modules/.bin/nodemon", "app"]
    ports:
      - "3333:3333"
  vue:
    build: vue/.
    volumes:
      - ./vue:/vue
    working_dir: /vue/frontapp
    command: ["npm", "run", "serve"]
    ports:
      - "8888:8888"
